### PR TITLE
TouchBar support

### PR DESCRIPTION
**Pull request by michaelsavich**
Preliminary TouchBar support for Transmission. Primarily concerned with mirroring the toolbar onto the TouchBar for easy access. 

There is currently no translation in this build. The TouchBar is wired up in each version of MainMenu.xib, but the customization labels are still in English. Also, I wired the xibs up using ctrl-clicking and dragging to IBOutlets, and though I double checked, it is probably worth triple checking that all of the localization xibs are wired up the same way the English one is.

### CODE REVIEW

**Comment by michaelsavich** [comment]
Whoops, I must have forgotten to upload the right files or something? I'll reopen this in a bit…

**Comment by michaelsavich** [comment]
All right I fixed the mistake-- I didn't realize I had to upload the mainmenu.xib to each respective lproj folder. It's up & working now, so I've reopened the pull request.

**Comment by mikedld** [comment]
Actually, you need to open PR in [upstream repository](https://github.com/transmission/transmission/pulls) (i.e. the repository you want your changes to end up), not in your own fork ;) Also, please
 * get rid of "Remove mistakenly added file" commit (rebase and squash it with the first commit where the file was added),
 * get rid of trailing whitespace in code (those myriads of blank green bars you see in b9a1e98950dfc92cc2f1d503d852d2c8b84ff134),
 * get rid of non-functional changes, i.e. added/removed blank lines,
 * follow existing coding style (newline before `{`, space after return/argument type and `:`); when in doubt (if existing code style contradicts itself), look for most frequently used style.

And if you can (and didn't do this yet), please test on OS versions other than 10.12 (e.g. 10.7 which is currently the minimum supported one, until PRs for transmission/transmission#140 come in).

**Comment by michaelsavich** [comment]
Thanks for the feedback. I'm really new to applied usage of Git/hub, so it's actually helpful. (I must have assumed that the "commit and open pull request" button would open a pull request upstream lol) 
I did see those green bars but was mystified by them as I don't recall ever editing any of those lines. Will fix them. Also yeah I'll squash down everything to one commit. 
Again thanks for the help this is literally my second time contributing to an open source project so I'll get better at it, promise ;).

**Pull request closed without merging**
